weights: ./YOGA-n.pt
cfg: ./models/YOGA-n.yaml
data: hripcb2.yaml
hyp: ./data/hyps/YOGA-n.yaml
epochs: 300
batch_size: 128
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: true
workers: 8
project: YOGA_pt
name: YOGA-n
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.01
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: YOGA_pt/YOGA-n
